backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\helpers\Json;
use common\models\Menu;
use common\models\Group;

class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'ajax-login', 'logout', 'timeout', 'error'],
                        'allow' => true
                    ],
                    [
                        'actions' => ['index', 'about', 'layout', 'git'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction'
            ]
        ];
    }

    public function actionIndex()
    {
        $this->layout = 'bjui';
        $query = Group::find();
        $models = $query->where(['pid'=>0])->with('groups')->all();
        return $this->render('index', [
            'models' => $models
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionLogin()
    {
        $this->layout = false;
        if (! \Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/');
        } else {
            return $this->render('login', [
                'model' => $model
            ]);
        }
    }

    public function actionAjaxLogin()
    {
        $this->layout = false;
        $model = new LoginForm();
        $data = [];
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $data['statusCode'] = 200;
            $data['message'] = '登陆成功';
            $data['closeCurrent'] = true;
            return Json::encode($data);
        } else {
            $data['statusCode'] = 300;
            $data['message'] = '登陆失败';
            return Json::encode($data);
        }
    }

    public function actionTimeout()
    {
        return $this->render('timeout');
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        $data = [
            'statusCode' => 200,
            'closeCurrent' => true,
            'message' => '注销成功'
        ];
        return Json::encode($data);
    }

    public function actionLayout()
    {
        return $this->render('layout');
    }
    
    public function actionGit()
    {
        return $this->render('git');
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
//         var_dump($model->errors);
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/about.php
<div class="bjui-pageContent">
    <form action="ajaxDone1.html" class="pageForm" data-toggle="validate">
        <table class="table table-condensed table-hover">
            <tbody>
                <tr>
                    <td colspan="2" align="center"><h3>公司名称</h3></td>
                </tr>
                <tr>
                    <td colspan="2" align="center"><p><br>这里是我的业务内容！</p></td>
                </tr>
            </tbody>
        </table>
    </form>
</div>
<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close">关闭</button></li>
    </ul>
</div>

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/git.php
<!-- for git 挂件 begin -->
<?php use yii\helpers\Url;?>
<script src='<?php echo Url::to('http://git.oschina.net/zhangchengbo/yii2-bjui/widget_preview')?>'></script>
<script src='<?php echo Url::to('http://git.oschina.net/xknaan/B-JUI/widget_preview')?>'></script>
<style type="text/css">
body {margin: 0;padding: 0;}
* {font-family: "Verdana", "Tahoma", "Lucida Grande", "Microsoft YaHei","Hiragino Sans GB", sans-serif;}
.pro_name a {color: #4183c4;}
.osc_git_title {padding: 2px 5px 0 !important;background-color: #d8e5f1;}
.osc_git_box {background-color: #fafafa;}
.osc_git_box {border-color: #ddd;}
.osc_git_info {color: #666;}
.osc_git_main a {color: #4183c4;font-size: 14px;line-height: 1.5;}
.osc_git_main li {line-height: 1.5;}
</style>

backend/views/site/layout.php
<?php use yii\helpers\Url; ?>
<div class="bjui-pageHeader" style="background: #FFF;">
    <div style="padding: 0 15px;">
        <h4 style="margin-bottom: 20px;">
            微信企业号管理平台 <small>轻松开发，专注您的业务！</small>
        </h4>
        <div style="float: left; width: 157px;">
            <div class="alert alert-info" role="alert" style="margin: 0 0 5px; padding: 10px;">
                <img src="images/ewm.png" width="135">
            </div>
        </div>
        <div style="margin-left: 170px; margin-top: 22px; padding-left: 6px;">
            <a target="_blank" href="http://shang.qq.com/wpa/qunwpa?idkey=eadb9e215426e734cf900ca9eda694b641d01dc2035577280e888e8df9d97be2">
                <img border="0" src="http://pub.idqqimg.com/wpa/images/group.png" alt="Yii2开发团队" title="Yii2开发团队">
            </a>
            <span style="padding-left: 10px;">官方网站：</span>
            <a href="http://www.hnqyw.com/" target="_blank">http://www.hnqyw.com/</a>
        </div>
        <div class="row" style="margin-left: 170px; margin-top: 10px;">
            <div class="col-md-6" style="padding: 5px;">
                <div class="alert alert-success" role="alert" style="margin: 0 0 5px; padding: 5px 15px;">
                    <strong>Yii2 - BJUI 团队欢迎你!</strong> <br> <span class="label label-default">开发：</span>
                    <a href="javascript:void(0);" target="_blank">@张成波 （河南郑州）</a>
                    <br> <span class="label label-default">测试 & 推广：</span>
                    <a href="javascript:void(0);">@张成波 （河南郑州）</a>
                    <br> <span class="label label-default">测试 & 试用：</span>
                    <a href="javascript:void(0);">@张成波 （河南郑州）</a>
                </div>
            </div>
            <div class="col-md-6" style="padding: 5px;">
                <div class="alert alert-info" role="alert" style="margin: 0 0 5px; padding: 5px 15px;">
                    <h5>
                        前台地址：
                        <a href="http://www.yj.mangxiaoquan.com" target="_blank">http://www.yj.mangxiaoquan.com</a>
                    </h5>
                    <h5>
                        API 地址：
                        <a href="http://api.yj.mangxiaoquan.com" target="_blank">http://api.yj.mangxiaoquan.com</a>
                    </h5>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="bjui-pageContent">
    <div style="margin-top: 5px; overflow: hidden;">
        <div class="row" style="padding: 0 2px;">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <i class="fa fa-list"></i> GIT@OSC 最新提交
                        </h3>
                    </div>
                    <div class="panel-body">
                        <iframe width="100%" height="600" class="share_self" frameborder="0" scrolling="auto" src="<?php echo Url::toRoute('site/git') ?>"></iframe>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <i class="fa fa-bar-chart-o fa-fw"></i> 当前版本：
                            <code>V1.0</code>
                            最近更新日志(2015-07-08)：
                        </h3>
                    </div>
                    <div class="panel-body bjui-doc" style="padding: 0;">
                        <ul>
                            <li>[修复]datagrid在local模式下提供空数据时显示不正常的bug</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use backend\assets\BjuiAsset;
BjuiAsset::register($this);
$baseUrl = $this->assetBundles[BjuiAsset::className()]->baseUrl . '/';

?>
<?php $this->beginPage()?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
<meta charset="<?= Yii::$app->charset ?>">
<title>系统登录</title>
<?php $this->head()?>
<style type="text/css">
* {
	font-family: "Verdana", "Tahoma", "Lucida Grande", "Microsoft YaHei",
		"Hiragino Sans GB", sans-serif;
}

body {
	background: url(images/loginbg_01.jpg) no-repeat center center fixed;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
}

a:link {
	color: #285e8e;
}

.main_box {
	position: absolute;
	top: 50%;
	left: 50%;
	margin-top: -260px;
	margin-left: -300px;
	padding: 30px;
	width: 600px;
	height: 460px;
	background: #FAFAFA;
	background: rgba(255, 255, 255, 0.5);
	border: 1px #DDD solid;
	border-radius: 5px;
	-webkit-box-shadow: 1px 5px 8px #888888;
	-moz-box-shadow: 1px 5px 8px #888888;
	box-shadow: 1px 5px 8px #888888;
}

.main_box .setting {
	position: absolute;
	top: 5px;
	right: 10px;
	width: 10px;
	height: 10px;
}

.main_box .setting a {
	color: #FF6600;
}

.main_box .setting a:hover {
	color: #555;
}

.login_logo {
	margin-bottom: 20px;
	height: 45px;
	text-align: center;
}

.login_logo img {
	height: 45px;
}

.login_msg {
	text-align: center;
	font-size: 16px;
}

.login_form {
	padding-top: 20px;
	font-size: 16px;
}

.login_box .form-control {
	display: inline-block;
	*display: inline;
	zoom: 1;
	width: auto;
	font-size: 18px;
}

.login_box .form-control.x319 {
	width: 319px;
}

.login_box .form-control.x164 {
	width: 164px;
}

.login_box .form-group {
	margin-bottom: 20px;
}

.login_box .form-group label.t {
	width: 120px;
	text-align: right;
	cursor: pointer;
}
.login_box .checkbox {
    margin-left: 120px;
}
.login_box .m {
	cursor: pointer;
}

.login_box .form-group.space {
	padding-top: 15px;
	border-top: 1px #FFF dotted;
}

.login_box .form-group p {
	margin-left: 120px;	
}
.login_box .form-group img {
	margin-top: 1px;
	height: 32px;
	vertical-align: top;
}


.bottom {
	text-align: center;
	font-size: 12px;
}
</style>
</head>
<body>
<?php $this->beginBody()?>
<!--[if lte IE 7]>
<style type="text/css">
#errorie {position: fixed; top: 0; z-index: 100000; height: 30px; background: #FCF8E3;}
#errorie div {width: 900px; margin: 0 auto; line-height: 30px; color: orange; font-size: 14px; text-align: center;}
#errorie div a {color: #459f79;font-size: 14px;}
#errorie div a:hover {text-decoration: underline;}
</style>
<div id="errorie"><div>您还在使用老掉牙的IE，请升级您的浏览器到 IE8以上版本 <a target="_blank" href="http://windows.microsoft.com/zh-cn/internet-explorer/ie-8-worldwide-languages">点击升级</a>&nbsp;&nbsp;强烈建议您更改换浏览器：<a href="http://down.tech.sina.com.cn/content/40975.html" target="_blank">谷歌 Chrome</a></div></div>
<![endif]-->
	<div class="main_box">
		<div class="setting">
			<a href="javascript:;" onclick="choose_bg();" title="更换背景"><span
				class="glyphicon glyphicon-th-large"></span></a>
		</div>
		<div class="login_box">
			<div class="login_logo">
				<img src="images/logo.png">
			</div>
			<div class="login_form">
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($model, 'username')->textInput(['class'=>'form-control x319 in input-nm'])->label('用户名',['class'=>'t'])?>
                <?= $form->field($model, 'password')->passwordInput(['class'=>'form-control x319 in input-nm'])->label('密　码',['class'=>'t'])?>
                <?= $form->field($model, 'rememberMe')->checkbox()->label('记住我的登陆状态',['class'=>'t m'])?>
				<div class="form-group space">
					<label class="t"></label>
                    <?= Html::submitButton('&nbsp;登&nbsp;录&nbsp;', ['class' => 'btn btn-primary btn-lg'])?>
                    <?= Html::resetButton('&nbsp;重&nbsp;置&nbsp;', ['class' => 'btn btn-default btn-lg'])?>
                </div>
            <?php ActiveForm::end(); ?>
            </div>
		</div>
		<div class="bottom">
			Copyright &copy; 2015 - 2016 <a href="http://www.yiichina.com">Yii2开发团队</a>
		</div>
	</div>
<?php $this->endBody()?>
<script type="text/javascript">
$(function() {
    choose_bg();
});
function choose_bg() {
	var bg = Math.floor(Math.random() * 9 + 1);
	$('body').css('background-image', 'url(images/loginbg_0'+ bg +'.jpg)');
}
</script>
</body>
</html>
<?php $this->endPage()?>

backend/views/site/timeout.php
<?php
use yii\helpers\Url;
?>
<div class="bjui-pageContent">
    <form action="<?= Url::toRoute('site/ajax-login') ?>" data-toggle="validate" method="post">
        <input name="_csrf" type="hidden" id="_csrf" value="<?= Yii::$app->request->csrfToken ?>">
        <div class="form-group">
            <label for="j_pwschange_oldpassword" class="control-label x85">用户名：</label>
            <input type="text" data-rule="required" name="LoginForm[username]" value="" placeholder="用户名" size="20">
        </div>
        <div class="form-group">
            <label for="j_pwschange_oldpassword" class="control-label x85">密码：</label>
            <input type="password" data-rule="required" name="LoginForm[password]" value="" placeholder="密码" size="20">
        </div>
    </form>
</div>
<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close">取消</button></li>
        <li><button type="submit" class="btn-default">提交</button></li>
    </ul>
</div>